package tn.esprit.pidev.Service;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.jboss.aerogear.security.otp.Totp;

/**
 * Test class for TwoFactorAuth
 */
public class TwoFactorAuthTest {

    /**
     * Test the validateCode method with a code generated by the AeroGear OTP library
     */
    @Test
    public void testValidateCodeWithAeroGear() {
        // Generate a secret key
        String secretKey = TwoFactorAuth.generateSecretKey();
        System.out.println("Generated secret key: " + secretKey);

        // Generate a TOTP code using the AeroGear OTP library
        Totp totp = new Totp(secretKey);
        String code = totp.now();
        System.out.println("Generated code from AeroGear: " + code);

        // Validate the code using our TwoFactorAuth class
        boolean isValid = TwoFactorAuth.validateCode(secretKey, code);
        System.out.println("Validation result: " + isValid);

        // Assert that the code is valid
        assertTrue(isValid, "The code generated by AeroGear should be valid");
    }

    /**
     * Test the validateCode method with an invalid code
     */
    @Test
    public void testValidateCodeWithInvalidCode() {
        // Generate a secret key
        String secretKey = TwoFactorAuth.generateSecretKey();

        // Use an invalid code (not matching the current time)
        String invalidCode = "000000";

        // Validate the code
        boolean isValid = TwoFactorAuth.validateCode(secretKey, invalidCode);

        // Assert that the code is invalid
        assertFalse(isValid, "An invalid code should not be validated");
    }
}
